cargo run --release --bin chokudai2 1 > out/1.txt &
cargo run --release --bin chokudai2 2 > out/2.txt &
cargo run --release --bin chokudai2 3 > out/3.txt &
cargo run --release --bin chokudai2 4 > out/4.txt &
cargo run --release --bin chokudai2 5 > out/5.txt &
cargo run --release --bin chokudai2 6 > out/6.txt &
cargo run --release --bin chokudai2 7 > out/7.txt &
cargo run --release --bin chokudai2 8 > out/8.txt &
cargo run --release --bin chokudai2 9 > out/9.txt &
cargo run --release --bin chokudai2 10 > out/10.txt &
cargo run --release --bin chokudai2 11 > out/11.txt &
cargo run --release --bin chokudai2 12 > out/12.txt &
cargo run --release --bin chokudai2 13 > out/13.txt &
cargo run --release --bin chokudai2 14 > out/14.txt &
cargo run --release --bin chokudai2 15 > out/15.txt &
cargo run --release --bin chokudai2 16 > out/16.txt &
cargo run --release --bin chokudai2 17 > out/17.txt &
cargo run --release --bin chokudai2 18 > out/18.txt &
cargo run --release --bin chokudai2 19 > out/19.txt &
cargo run --release --bin chokudai2 20 > out/20.txt &
cargo run --release --bin chokudai2 21 > out/21.txt &
cargo run --release --bin chokudai2 22 > out/22.txt &
cargo run --release --bin chokudai2 23 > out/23.txt &
cargo run --release --bin chokudai2 24 > out/24.txt &
cargo run --release --bin chokudai2 25 > out/25.txt &
cargo run --release --bin chokudai2 26 > out/26.txt &
cargo run --release --bin chokudai2 27 > out/27.txt &
cargo run --release --bin chokudai2 28 > out/28.txt &
cargo run --release --bin chokudai2 29 > out/29.txt &
cargo run --release --bin chokudai2 30 > out/30.txt &
cargo run --release --bin chokudai2 31 > out/31.txt &
cargo run --release --bin chokudai2 32 > out/32.txt &
cargo run --release --bin chokudai2 33 > out/33.txt &
cargo run --release --bin chokudai2 34 > out/34.txt &
cargo run --release --bin chokudai2 35 > out/35.txt &
wait	