name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UNAGI_PASSWORD: ${{ secrets.UNAGI_PASSWORD }}
  DOCKER_BUILDKIT: 1

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Cache Rust crates
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: make test/rust

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Run tests
        run: make test/go

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test/secrets

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build an image
        run: make docker/server

  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Set up credentials
        run: make secrets/service_account.json
      - name: Build an image
        run: make docker/runner

  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Set up credentials
        run: make secrets/service_account.json
      - name: Build an image
        run: make docker/builder
      - name: Deploy binaries
        run: |
          docker run --rm icfpc-unagi/builder \
              bash /work/scripts/deploy_binaries.sh \
              "$(git rev-parse --short HEAD)"
