name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UNAGI_PASSWORD: ${{ secrets.UNAGI_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rust:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs tests
      - name: Run tests
        run: make test/rust

  go:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Run tests
        run: make test/go

  secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs tests
      - name: Run tests
        run: make test/secrets

  builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build binaries
        run: |
          make secrets/service_account.json && \
          make docker/builder && \
          docker run --rm icfpc-unagi/builder \
              bash /work/scripts/deploy_binaries.sh \
              "$(git rev-parse --short HEAD)"

  runner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build an image
        run: |
          make secrets/service_account.json && \
          make docker/runner
